### ISSUE TITLE
i prefer you to examine this

### ISSUE THREAD

**Issue by OguzhanUmutlu** [fishuke/getir-clone#13]
[5651st Law](https://www.mevzuat.gov.tr/MevzuatMetin/1.5.5651.pdf)

**Comment by fishuke** [comment]
Hello,  thanks for brining this issue here. Can you provide more information?

**Comment by OguzhanUmutlu** [comment]
You should not publish getir's recoded code

**Comment by fishuke** [comment]
If we violate Getir's trademark rights, they can request removal by contacting us. I couldn't find anything wrong here. You can be more spesific about law. I can not read all of these papers.
